import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import black, white, Color

OUTPUT_FOLDER = "assets"
OUTPUT_FILE = os.path.join(OUTPUT_FOLDER, "application_form.pdf")

def create_english_template():
    # Ensure folder exists
    if not os.path.exists(OUTPUT_FOLDER):
        os.makedirs(OUTPUT_FOLDER)

    c = canvas.Canvas(OUTPUT_FILE, pagesize=A4)
    width, height = A4
    
    # --- STYLING ---
    TITLE_FONT = "Helvetica-Bold"
    TEXT_FONT = "Helvetica"
    
    # Draw Border
    margin = 40
    c.setStrokeColor(black)
    c.setLineWidth(1)
    c.rect(margin, margin, width - (2*margin), height - (2*margin))

    # --- HEADER ---
    c.setFont(TITLE_FONT, 16)
    c.drawCentredString(width / 2, height - 80, "APPLICATION FOR IDENTITY CARD")
    
    c.setFont(TEXT_FONT, 10)
    c.drawCentredString(width / 2, height - 100, "(For minors turning 14 years old)")
    
    c.line(margin, height - 120, width - margin, height - 120)

    # --- HELPER: Draw Section Header ---
    def draw_section(y, title):
        # Grey Bar Background
        c.setFillColor(Color(0.9, 0.9, 0.9))
        c.rect(margin, y - 5, width - (2*margin), 20, fill=1, stroke=1)
        # Text
        c.setFillColor(black)
        c.setFont(TITLE_FONT, 11)
        c.drawString(margin + 10, y + 2, title)
        return y - 35

    # --- HELPER: Draw Input Field ---
    def draw_field(y, label, key):
        # 1. Draw Label
        c.setFont(TEXT_FONT, 10)
        c.drawString(margin + 20, y, label)
        
        # 2. Draw Visual Line (Guide)
        field_x = margin + 120
        field_width = (width - margin - 40) - field_x
        
        c.setStrokeColor(Color(0.6, 0.6, 0.6)) 
        c.line(field_x, y - 2, field_x + field_width, y - 2)
        
        # 3. Create Fillable Box (The Fix is here!)
        c.acroForm.textfield(
            name=key,
            tooltip=label,
            x=field_x, 
            y=y - 2, 
            width=field_width, 
            height=16,
            fontSize=10,
            fontName=TEXT_FONT,
            borderStyle='solid',     # <--- FIXED: Changed 'beveled' to 'solid'
            borderColor=white,       # Hidden border (white) so it looks like just a line
            forceBorder=False
        )
        return y - 30

    # --- DRAWING THE FORM ---
    current_y = height - 160

    # Section 1
    current_y = draw_section(current_y, "I. PERSONAL DATA")
    current_y = draw_field(current_y, "Last Name:", "LastName")
    current_y = draw_field(current_y, "First Name:", "FirstName")
    current_y = draw_field(current_y, "Personal ID (CNP):", "CNP")

    # Section 2
    current_y -= 10
    current_y = draw_section(current_y, "II. PARENTS' DATA")
    current_y = draw_field(current_y, "Father's Name:", "FatherName")
    current_y = draw_field(current_y, "Mother's Name:", "MotherName")

    # Section 3
    current_y -= 10
    current_y = draw_section(current_y, "III. DOMICILE ADDRESS")
    
    # Custom layout for City/Sector
    c.setFont(TEXT_FONT, 10)
    c.drawString(margin + 20, current_y, "City / Sector:")
    
    c.acroForm.textfield(
        name="City", 
        x=margin+100, 
        y=current_y-2, 
        width=150, 
        height=16, 
        fontName=TEXT_FONT, 
        fontSize=10,
        borderStyle='solid',       # <--- FIXED
        borderColor=white
    )
    c.line(margin+100, current_y-2, margin+250, current_y-2)
    
    current_y -= 30
    current_y = draw_field(current_y, "Street Name:", "Street")
    current_y = draw_field(current_y, "Number / Bl / Ap:", "Number")

    # --- FOOTER ---
    c.setFont(TEXT_FONT, 8)
    c.drawCentredString(width/2, margin + 15, "Generated by AI Agent - Proof of Concept")

    c.save()
    print(f"✅ ENGLISH Template created: {OUTPUT_FILE}")

if __name__ == "__main__":
    create_english_template()